# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e5cbcd9e8dfb90a6c0cd03a7b6bdacbb009db190cff9da083bd2f9b6f84b5a52f01f79d072131a982fb1a5d7735b94d7a5d757f1a0b4418ef3ede106e63cb08

test:
  secret_key_base: 7853bdfaaaeb6c3dd8fcb5c71903840976be003620174899d997d9731445aa06d34ff5159a2ca31002dcfe273ed6641d405d38ec0074f601c87985453835d972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
